### ISSUE TITLE
Where to include PATH for sox install?

### ISSUE THREAD

**Issue by vtange** [psaylor/sox-audio#2]
Another user and I have looked into your project as a way of including SoX into our projects but can't seem to figure out where we can link up sox.exe to your module.

I'm guessing it's "soxPath" in processor.js
I'm using a Windows portable version of SoX (14.4.2-win32) 

I made a temporary "it works" fix for myself. You can find it on #1

**Comment by psaylor** [comment]
Hey Victor, my module requires SoX to be installed and in your PATH so that the module can find it with the UNIX `which` command. Unfortunately Windows does not use UNIX commands (yet), so the equivalent command on Windows would be `where`. Overwriting `soxPath` in `processor.js` may work fine for you, but another solution would be to ensure SoX is in your PATH and then modify the function `utils.which` in `utils.js` to use the Windows `where` command instead of the UNIX `which` command (https://github.com/psaylor/sox-audio/blob/master/lib/utils.js#L44). An ideal solution would detect the OS being used and then determine the appropriate command.
